# Generated by Django 3.2.6 on 2021-08-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='greetings_1',
            new_name='intro',
        ),
    ]
