# Generated by Django 3.2.6 on 2021-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
