# Generated by Django 3.2.6 on 2021-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
