# Generated by Django 3.2.6 on 2021-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210818_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='DEFAULT', upload_to='portfolio/'),
        ),
    ]
