# Generated by Django 3.2.6 on 2021-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
