# Generated by Django 3.2.6 on 2021-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_experience_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='job_desciption',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_responsibility',
            field=models.CharField(default='', max_length=200),
        ),
    ]
