# Generated by Django 3.2.6 on 2021-09-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='update_time',
        ),
    ]
