# Generated by Django 3.2.6 on 2021-09-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_home_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
