# Generated by Django 3.2.6 on 2021-09-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_home_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='picture',
        ),
    ]
